# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
x = np.random.rand(3,3)
x

array([[0.83312232, 0.33615755, 0.00177245],
       [0.01605449, 0.3850665 , 0.51707656],
       [0.50182914, 0.81974937, 0.68846145]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [22]:
import numpy as np
x = np.array([[1,0,0,0,0],
             [1,1,0,0,0],
             [1,2,1,0,0],
            [1,2,3,1,0],
            [1,2,3,4,1]])
x

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 2, 1, 0, 0],
       [1, 2, 3, 1, 0],
       [1, 2, 3, 4, 1]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [23]:
import numpy as np
# function to print Checkerboard pattern 
def printcheckboard(n): 
      
    print("Checkerboard pattern:") 
  
    # create a n * n matrix 
    x = np.zeros((n, n), dtype = int) 
  
    # fill with 1 the alternate rows and columns 
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
      
    # print the pattern 
    for i in range(n): 
        for j in range(n): 
            print(x[i][j], end =" ")  
        print()  
  
  
# driver code 
n = 8
printcheckboard(n) 

Checkerboard pattern:
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


# 4. Normalize a 5x5 random matrix

In [27]:
import numpy as np
x = np.random.rand(5,5)

xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

After normalization:
[[0.25974792 0.14426964 0.25735486 0.9812332  0.62732942]
 [0.0203712  0.48853234 0.69077914 1.         0.92033378]
 [0.55415427 0.23687252 0.95173512 0.         0.23707396]
 [0.3604638  0.301279   0.47143607 0.42210775 0.11809123]
 [0.75980948 0.08541193 0.18703815 0.76205137 0.09472818]]


# 5.  How to find common values between two arrays?

In [28]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [29]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [30]:
an_array = np.array([[1,2],[3,4]])
another_array = np.array([[1,2],[3,4]])

comparison = an_array == another_array
equal_arrays = comparison.all()

print(equal_arrays)

True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [37]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.02951612 0.74435358 0.97838008 0.1010738  0.6918499  0.64013751
 0.91916103 0.53235925 0.88797452 0.4653536 ]
Maximum value replaced by 0:
[0.02951612 0.74435358 0.         0.1010738  0.6918499  0.64013751
 0.91916103 0.53235925 0.88797452 0.4653536 ]


# 9. How to print all the values of an array?

In [38]:
import numpy as np
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [3]:
import numpy as np
x = np.random.rand(3,3)
print("original matrix")
print(x)
print("subtract the eman of each row of given matrix")
y = x - x.mean(axis=1, keepdims=True)
print(y)


original matrix
[[0.34342349 0.8021819  0.03895613]
 [0.095016   0.64051555 0.66696408]
 [0.87857311 0.80551854 0.83238806]]
subtract the eman of each row of given matrix
[[-0.05143035  0.40732806 -0.35589771]
 [-0.37248254  0.17301701  0.19946554]
 [ 0.03974654 -0.03330803 -0.00643851]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [29]:
import numpy as np
a = np.random.rand(3,3)
b = np.random.rand(3,3)
print(a)
print(b)
x = a + 1
x
 


[[0.89559255 0.41344887 0.32260175]
 [0.3073408  0.51177255 0.21820932]
 [0.03678523 0.51583361 0.98607543]]
[[0.07598403 0.17303586 0.59682837]
 [0.91955616 0.04508705 0.58217701]
 [0.50681876 0.92627706 0.79364661]]


array([[1.89559255, 1.41344887, 1.32260175],
       [1.3073408 , 1.51177255, 1.21820932],
       [1.03678523, 1.51583361, 1.98607543]])

# 12.How to get the diagonal of a dot product?

In [11]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]])
print("a")
print(a)
print("b")
print(b)
print("Diagonal of a")
a1 = a.diagonal()
print(a1)
print("Diagonal of b")
b1 = a.diagonal()
print(b1)
z = np.dot(a1,b1)
z

a
[[1 2]
 [3 4]]
b
[[11 12]
 [13 14]]
Diagonal of a
[1 4]
Diagonal of b
[1 4]


17

# 13.How to find the most frequent value in an array?

In [20]:
import numpy as np
from scipy import stats

a = np.array([[1, 3, 4, 2, 2, 7],
              [5, 2, 2, 1, 4, 1],
              [3, 3, 2, 2, 1, 1]])

m = stats.mode(a)
print(m)


ModeResult(mode=array([[1, 3, 2, 2, 1, 1]]), count=array([[1, 2, 2, 2, 1, 2]]))


# 14.How to get the n largest values of an array

In [23]:
import numpy as np
a = np.random.rand(3,3)
print("original ")
print(a)
y = a.max()
print("The largest value is:")
print(y)

original 
[[0.03178673 0.39954133 0.42830305]
 [0.43212613 0.84819327 0.76833458]
 [0.41777128 0.87504018 0.14465568]]
The largest value is
0.8750401762779985


# 15.How to create a record array from a regular array?

In [24]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
